// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAbDMD_cfYaNBBUJg2a-fr7_35gXAQTeG0',
    appId: '1:1048094662586:web:3b9c21e323489d824cc783',
    messagingSenderId: '1048094662586',
    projectId: 'fir-sample1-99921',
    authDomain: 'fir-sample1-99921.firebaseapp.com',
    storageBucket: 'fir-sample1-99921.appspot.com',
    measurementId: 'G-3EPQ8F0516',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCyS4DO_kHRte1Ajed9CPWw0c1qrUXIinA',
    appId: '1:1048094662586:android:453dc72580f991e64cc783',
    messagingSenderId: '1048094662586',
    projectId: 'fir-sample1-99921',
    storageBucket: 'fir-sample1-99921.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAAyeMoDaiXl7jowx51cQ9Xr2RQyQAzNyM',
    appId: '1:1048094662586:ios:450b85727b648ebd4cc783',
    messagingSenderId: '1048094662586',
    projectId: 'fir-sample1-99921',
    storageBucket: 'fir-sample1-99921.appspot.com',
    iosBundleId: 'com.example.firebaseSample1',
  );
}
