// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_KKCKUdeNWH5bR-UTR6-KMgyRcK5trfk',
    appId: '1:136094471980:web:8cfec3ee8ca8643d9bbe89',
    messagingSenderId: '136094471980',
    projectId: 'tjoeun3joproject',
    authDomain: 'tjoeun3joproject.firebaseapp.com',
    storageBucket: 'tjoeun3joproject.appspot.com',
    measurementId: 'G-DR2BLH4EMB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCs7TY8mHqilIOAzmXOuwT-a7ZsEC2qCbA',
    appId: '1:136094471980:android:ebaad182718e2dfc9bbe89',
    messagingSenderId: '136094471980',
    projectId: 'tjoeun3joproject',
    storageBucket: 'tjoeun3joproject.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCggBdCDthfK_zX06pfCt99dNM22uEfZ50',
    appId: '1:136094471980:ios:8b78ce2edcd4187f9bbe89',
    messagingSenderId: '136094471980',
    projectId: 'tjoeun3joproject',
    storageBucket: 'tjoeun3joproject.appspot.com',
    iosBundleId: 'com.example.foodMarvel',
  );
}
